root: true
plugins: []
extends:
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:nuxt/recommended'
  - 'prettier'
env:
  browser: true
  node: true
rules:
  # See https://github.com/vuejs/eslint-plugin-vue/issues/1577
  import/first: 0
  import/no-named-as-default-member: 0
  no-console:
    - 'error'
    - allow:
        - 'warn'
        - 'error'
